title = "foxinwinter"
base_url = "https://foxinwinter.github.io"
description = "Silly little website for a silly little guy :p"

theme = "ametrine"

compile_sass = true
minify_html = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = true
author = "foxinwinter"

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "categories", feed = true },
]

[markdown]
render_emoji = false
smart_punctuation = true
lazy_async_image = false
bottom_footnotes = true
external_links_class = "external"
github_alerts = true

[markdown.highlighting]
style = "class"
light_theme = "monokai-pro-light"
dark_theme = "monokai-pro"
extra_themes = [
  "themes/ametrine/giallo/themes/monokai-pro-light.json",
  "themes/ametrine/giallo/themes/monokai-pro.json",
]

[search]
index_format = "elasticlunr_json"

[extra]
categories = [
  { name = "Archived", description = "Posts that have been archived due to their age.", color = "purple", icon = "box-arrow-down" },
  { name = "Featured", description = "Posts that are somewhat decently written.", color = "yellow", icon = "star" },
  { name = "Hot", description = "Posts that did numbers compared to others.", color = "red", icon = "fire" },
  { name = "Test", description = "Categories can be set and customized entirely from config, woo-hoo!", color = "green", icon = "feather" },
]
# accent_color = "<red, orange, yellow, green, blue, purple>"
# Rum, London Hue
accent_color = ["hsl(270 60% 50%)", "hsl(280 50% 65%)"]
# home_url = "@/home/index.md"
issues_url = "https://github.com/foxinwinter/foxinwinter.github.io/issues/new"
source_url = "https://github.com/foxinwinter/foxinwinter.github.io"
show_copy_button = true
show_reading_time = true
show_backlinks = true
date_format = "%d %B %Y"
date_format_long = "%d %B %Y, %R (%Z)"
date_locale = "en_IE"
timezone = "America/Chicago"
show_comments_qr = true
csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "style-src", domains = [
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "frame-src", domains = [
    "www.youtube-nocookie.com",
    "incr.easrng.net",
    "vmst.io",
    "drive.google.com",
    "open.spotify.com",
  ] },
  { directive = "connect-src", domains = [
    "status.cafe",
    "api.lanyard.rest",
    "ws.audioscrobbler.com",
    "discord.com",
    "api.github.com",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.meta]
favicon = "favicon.gif"
apple_touch_icon = true
card = true

[extra.nav]
icon = "apple-touch-icon.png"
links = [
  { name = "Writing", category = [
    { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
    { url = "@/nanolog/_index.md", name = "Nanolog", icon = "note-pencil" },
  ] },
  { name = "Projects", category = [
    # { url = "@/calendar/index.md", name = "Calendar", icon = "calendar-dots" },
    { url = "https://example.com", name = "placeholder", icon = "traffic-cone" },
  ] },
  { name = "Extra", closed = true, category = [
    { url = "@/About+Credits/index.md", name = "About / Credits", icon = "question" },
  ] },
]

[extra.footer]
copyright = false
show_fediring = false
show_timestamp = true
show_powered_by = true
socials = [
  { url = "https://github.com/foxinwinter", icon = "github" },
]

[extra.analytics]
service = "umami"
id = "52d85500-dfcc-4677-80b0-89f72ba84e2a"
self_hosted_url = ""
do_not_track = false

[extra.debug]
layout = false
no_styles = false
no_emojis = false
