name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.repository }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
