name: Build

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}

    steps:
      - name: Install base packages
        run: |
          pacman -Sy --noconfirm git base-devel sudo

      - name: Create builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Install yay
        run: |
          su builder -c "git clone https://aur.archlinux.org/yay.git"
          su builder -c "cd yay && makepkg -si --noconfirm"

      - name: Install Zola
        run: |
          su builder -c "yay -S --noconfirm zola"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          chown -R builder:builder .

      - name: Build site
        run: |
          su builder -c "zola build"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
